### ISSUE TITLE
给组件设置默认值，组件开启搜索功能 搜索数据错乱

### ISSUE THREAD

**Issue by jxchenoct** [lquan529/cityPicker#10]
![1593328526(1)](https://user-images.githubusercontent.com/37365760/85940945-3839f280-b952-11ea-88ef-c700a5b85d33.jpg)
在默认值的情况下城市，和区域的搜索数据错乱
求大佬解决

      search: function (event) {
          event.preventDefault();
          var self = this,
              $target = $(event.target),
              $parent = $target.parents('.listing'),
              inputVal = $target.val(),
              id = $parent.data('id'),
              keycode = event.keyCode,
              result = [], htmls;
          暂时在search中加了这段代码是可行的
        **if($target.parents('.selector-item').data('index')!=0){
        id =$(`.selector-item[data-index=${$target.parents('.selector-item').data('index')-1}]`).children('.input-price').val()
        }**

**Comment by lquan529** [comment]
新版本v2.0.5 解决了这个问题
