### ISSUE TITLE
发现了几个bug,一个是在jquery-1.12.4 这个版本下, setCityVal 这个方法设置的省市区是反的

### ISSUE THREAD

**Issue by osgochina** [lquan529/cityPicker#2]
发现了几个bug,一个是在jquery-1.12.4 这个版本下, setCityVal 这个方法设置的省市区是反的.
第二个bug,416行getCityVal 方法,有问题,如果我不先改省,只改最后的区,那么是获取不到修改的值的.
我把代码修改成 
getCityVal: function () {
            var cityArray = this.values;
            // 如果是选择的就用选择
            if (this.province) {
                cityArray[0] = this.province;
            }
            if (this.city) {
                cityArray[1] = this.city;
            }
            if (this.district) {
                cityArray[2] = this.district;
            }
            return cityArray;
        }
我的修改比较粗糙,你可以按修复下这个bug

**Comment by lquan529** [comment]
第一个问题1.1.7 已经修复了，第二个问题我在看下吧，谢谢反馈

**Comment by osgochina** [comment]
第一个问题我就是在1.1.7下重现的,你换成jquery-1.12.4 这个版本测试下

**Comment by lquan529** [comment]
问题解决了，这个问题是因为我的一个东西写错造成的，getCityVal()这个问题也解决了
