### ISSUE TITLE
CSS 样式太多没必要的东西了

### ISSUE THREAD

**Issue by Han-MeiM** [lquan529/cityPicker#3]
CSS文件里面第一行就定义了太多没必要的元素样式，把我自己的布局都大乱了，太夸张了

**Comment by lquan529** [comment]
大佬，本身就是把demo的样式和组件的样式放在一起了，sass本身就有注释，说明那段是城市的样式的了，你自己把现在的css引入进去，肯定是有问题的了。现在我重新更新了，把城市的sass文件独立了，名字是_cityPicker.scss。如果你是用sass就直接把这个放到你的sass去，然后import进去就可以了

**Comment by wigginZhang** [comment]
大佬 city-picker.css文件没有上传啊
