### ISSUE TITLE
shorthand:true 时，为什么第四级出错

### ISSUE THREAD

**Issue by erastudio** [lquan529/cityPicker#4]
您好：
shorthand:true 时，第四级显示出错
<select name="userStreet" data-index="3" class="street">
<option class="caller" value="">请选择街道</option>
<option class="caller" value="140109001" data-id="140109001" data-title="undefined">undefined</option>

**Comment by lquan529** [comment]
这个我忘记判断了，因为四级的数据是从别人收集哪里来的，不是我的，所以是没有简写的

**Comment by erastudio** [comment]
恩，整体挺好用的，辛苦了，期待一些细节更新。

**Comment by lquan529** [comment]
谢谢！
版本已经更新了v-2.0.1 修改了这个bug
