### ISSUE TITLE
storage:false 时 setCityVal 如何通过数字来设置默认城市

### ISSUE THREAD

**Issue by erastudio** [lquan529/cityPicker#5]
select.setCityVal('230000,230400,230404');

能否实现这样的效果。

**Comment by erastudio** [comment]
storage:false 因为存到数据库的只有数字参数

**Comment by lquan529** [comment]
好的，这个我到时候加上

**Comment by erastudio** [comment]
恩，整体挺好用的，辛苦了，期待一些细节更新。

**Comment by lquan529** [comment]
谢谢！
版本已经更新到v-2.0.1
已经增加了这个功能

select.setCityVal('230000,230400,230404');

就可以实现设置城市
