### ISSUE TITLE
4级联动用名称setCityVal的一个bug

### ISSUE THREAD

**Issue by lihai410643776** [lquan529/cityPicker#8]
4级联动时，当使用setCityVal方法设置默认的城市时，如果是直辖市，即天津市,天津市,河西区,陈塘庄街道这类的数据，显示会出现错误，看了一下老兄源码，在dataJson时，如果是名称匹配，result数组中会多出两个元素，省级和市级各多了一个，导致显示错误，期待更正

**Comment by lquan529** [comment]
已解决，版本是v2.0.4
